[1] "Programme: 02-Traitements_fichiers_XML_MESH"
[1] "Heure lancement: "
[1] "2022-01-24 17:23:33"
[1] "Lecture des données"
[1] "Génération des paires"
[1] "31 fichiers à générer"
[1] "Split des données et écriture dans un .xml spécifique"
[1] "Fichier : 1"
[1] "Fichier : 2"
[1] "Fichier : 3"
[1] "Fichier : 4"
[1] "Fichier : 5"
[1] "Fichier : 6"
[1] "Fichier : 7"
[1] "Fichier : 8"
[1] "Fichier : 9"
[1] "Fichier : 10"
[1] "Fichier : 11"
[1] "Fichier : 12"
[1] "Fichier : 13"
[1] "Fichier : 14"
[1] "Fichier : 15"
[1] "Fichier : 16"
[1] "Fichier : 17"
[1] "Fichier : 18"
[1] "Fichier : 19"
[1] "Fichier : 20"
[1] "Fichier : 21"
[1] "Fichier : 22"
[1] "Fichier : 23"
[1] "Fichier : 24"
[1] "Fichier : 25"
[1] "Fichier : 26"
[1] "Fichier : 27"
[1] "Fichier : 28"
[1] "Fichier : 29"
[1] "Fichier : 30"
[1] "Fichier : 31"
Error in traitements_xml_fic(full_xml_database = fic, chemin = chemin_mesh_rds,  : 
  impossible de trouver la fonction "traitements_xml_fic"
Erreur : '=' inattendu(e) in:
"      tableau_dt2 <- tableau_dt2 %>% 
        mutate(get(name_id)="
Error in rbind(tableau_dt_final, tableau_dt2) : 
  objet 'tableau_dt_final' introuvable
Erreur : '}' inattendu(e) in "    }"
Error in paste0(chemin, nom, i_lot, ".RDS") : objet 'chemin' introuvable
Erreur : '}' inattendu(e) in "  }"
Erreur : '}' inattendu(e) in "}"
Erreur : objet 'traitements_xml_fic' introuvable
